name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check code generation
        run: |
          pnpm gen
          git diff --exit-code || (echo "Generated code is out of date. Please run 'pnpm gen' and commit the changes." && exit 1)

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build || true # allow missing build tasks early phases

      - name: Test
        run: pnpm test || true # allow no tests initially

      # --- Phase 2 additions: cross-lang tests & SBOM ---

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e './packages/aid-py[dev]' pytest

      - name: Test (Python)
        run: python -m pytest packages/aid-py

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test (Go)
        run: |
          cd packages/aid-go
          go test ./...

      - name: Generate SBOM (CycloneDX)
        uses: CycloneDX/gh-node-module-generatebom@v1
        with:
          output: ./sbom.xml

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
