name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # ---- static checks ----------------------------------------------------
      - name: Generate constants
        run: pnpm gen

      - name: Verify generated code committed
        run: |
          git diff --exit-code || \
          (echo "::error::Generated code is out of date. Run 'pnpm gen' and commit." && exit 1)

      - name: Lint (ESLint flat config)
        run: pnpm lint

      # ---- build & JS/TS tests ---------------------------------------------
      - name: Build
        run: pnpm build || true # allow packages without build yet

      - name: Test (JS/TS)
        run: pnpm test || true # allow zero tests early on

      # ---- cross-language phase-2 checks -----------------------------------
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Test (Python)
        run: |
          python -m pip install -e './packages/aid-py[dev]' pytest
          python -m pytest packages/aid-py

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test (Go)
        run: |
          cd packages/aid-go
          go test ./...

      - name: E2E Tests
        run: pnpm e2e

      # ---- SBOM ------------------------------------------------------------
      - name: Generate SBOM (CycloneDX)
        uses: CycloneDX/gh-node-module-generatebom@v1
        with:
          output: ./sbom.xml

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
